# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GPSTrackDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GPSTrackDemo
pod 'Alamofire'
pod 'TPKeyboardAvoiding'
pod 'SVProgressHUD'
pod 'GoogleMaps'

  target 'GPSTrackDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GPSTrackDemoUITests' do
    # Pods for testing
  end

end
